#cloud-config
hostname: {{ hostname }}
manage_etc_hosts: true

# cloud-init generates netplan config but won't activate it (bringup=False)
# because it doesn't consider packages/runcmd as "network requiring elements".
# bootcmd runs on every boot (including after reboots) and applies the config.
bootcmd:
  - rfkill unblock wifi
  - netplan apply

users:
  - name: tim
    gecos: Tim Ansell
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    groups: adm, dialout, cdrom, sudo, audio, video, plugdev, games, users, input, render, netdev, gpio, i2c, spi
    lock_passwd: true
    ssh_authorized_keys:
{% for key in ssh_keys %}
      - {{ key }}
{% endfor %}

ssh:
  install_server: true
  emit_keys_to_console: false

package_update: true
package_upgrade: true
packages:
  - git
  - build-essential
  - dkms

runcmd:
  - systemctl enable --now getty@ttyGS0.service
  - git clone https://github.com/Seeed-Studio/seeed-linux-dtoverlays /opt/seeed-linux-dtoverlays
  - cd /opt/seeed-linux-dtoverlays && sudo ./scripts/reTerminal.sh --keep-kernel
  - reboot
